name: Todoist completed today
description: ""
tableName: fct_habit
updatedAt: "2025-11-02T04:42:10.904Z"
metricQuery:
  exploreName: fct_habit
  dimensions:
    - dim_project_todoist_name
    - fct_habit_is_completed
    - fct_habit_scheduled_date_day
  metrics:
    - fct_habit_total_task_instances
  filters:
    dimensions:
      id: 96ba234f-970f-436f-ab54-05c4342a2d16
      and:
        - id: 1d38e2c1-32b1-4e20-a859-9b9078ecf3ed
          target:
            fieldId: fct_habit_scheduled_date_day
          values:
            - 1
          operator: inTheCurrent
          required: false
          settings:
            completed: false
            unitOfTime: days
        - id: 3fe49e41-60f2-40c3-a622-a86398802d50
          target:
            fieldId: fct_habit_is_completed
          values:
            - completed
          operator: equals
          required: false
  sorts:
    - fieldId: fct_habit_scheduled_date_day
      descending: true
  limit: 500
  metricOverrides: {}
  tableCalculations: []
  additionalMetrics: []
  customDimensions: []
chartConfig:
  type: pie
  config:
    isDonut: true
    metricId: fct_habit_total_task_instances
    showValue: true
    showLegend: true
    valueLabel: inside
    groupFieldIds:
      - dim_project_todoist_name
    legendPosition: horizontal
    showPercentage: false
    groupSortOverrides: []
    groupColorOverrides: {}
    groupLabelOverrides: {}
    legendMaxItemLength: 30
    groupValueOptionOverrides: {}
slug: copy-of-todoist-completion-rate-today-1762012024749
tableConfig:
  columnOrder:
    - dim_project_todoist_name
    - fct_habit_is_completed
    - fct_habit_scheduled_date_day
    - fct_habit_total_task_instances
spaceSlug: shared
version: 1
downloadedAt: "2025-11-02T04:42:21.039Z"
