name: ticktick - empty projects to be cleaned
description: ""
tableName: fct_tasks
updatedAt: "2025-11-09T02:27:21.968Z"
metricQuery:
  exploreName: fct_tasks
  dimensions:
    - dim_folders_folder_name
    - dim_projects_project_name
    - dim_projects_project_id
  metrics:
    - fct_tasks_total_task_instances
  filters:
    metrics:
      id: 055be4e7-123f-4ea8-9867-7ef7e5633649
      and:
        - id: f49cc8d1-fb10-4453-91a0-ad0a9300b72a
          target:
            fieldId: fct_tasks_total_task_instances
          values:
            - "0"
          operator: equals
    dimensions:
      id: 75529e08-d6d0-4223-bdec-fb18d79be718
      and:
        - id: 1ec3dcda-4f5c-469b-9d4b-5a54ba55f879
          target:
            fieldId: dim_folders_folder_name
          values:
            - üöÄSOMEDAY lists
            - üõ©Ô∏èHorizon of focus
            - default
            - üí§on hold lists
          operator: notEquals
          required: false
        - id: 99088be2-b65c-4eca-b8f0-34be6f1ca179
          target:
            fieldId: dim_tags_tag
          values:
            - default
            - clarified
          operator: equals
          required: false
        - id: f0737e4a-d357-4e58-834d-512d214112f5
          target:
            fieldId: dim_projects_closed
          values:
            - false
          operator: equals
          required: false
  sorts:
    - fieldId: dim_folders_folder_name
      descending: false
    - fieldId: fct_tasks_total_task_instances
      descending: false
  limit: 500
  metricOverrides: {}
  tableCalculations: []
  additionalMetrics: []
  customDimensions: []
chartConfig:
  type: table
  config:
    columns:
      dim_folders_folder_name:
        name: folder
      dim_projects_project_id:
        visible: false
      dim_projects_project_name:
        name: project
      fct_tasks_total_task_instances:
        name: tasks
    metricsAsRows: false
    showSubtotals: false
    hideRowNumbers: true
    showTableNames: false
    showResultsTotal: false
    showRowCalculation: false
    showColumnCalculation: false
    conditionalFormattings: []
slug: ticktick-empty-projects-to-be-cleaned
tableConfig:
  columnOrder:
    - dim_folders_folder_name
    - dim_projects_project_name
    - dim_projects_project_id
    - fct_tasks_total_task_instances
spaceSlug: shared
version: 1
downloadedAt: "2025-11-09T03:40:27.216Z"
