name: Todoist new today
description: ""
tableName: fct_habit
updatedAt: "2025-11-01T17:02:21.946Z"
metricQuery:
  exploreName: fct_habit
  dimensions:
    - dim_project_todoist_name
    - fct_habit_is_completed
    - fct_habit_scheduled_date_day
  metrics:
    - fct_habit_total_task_instances
  filters:
    dimensions:
      id: 1406e3e8-5acf-429d-8776-a64ce3296160
      and:
        - id: 1d38e2c1-32b1-4e20-a859-9b9078ecf3ed
          target:
            fieldId: fct_habit_scheduled_date_day
          values:
            - 1
          operator: inTheCurrent
          required: false
          settings:
            completed: false
            unitOfTime: days
        - id: c8ef8ac6-5f2d-4da0-8234-ca9537efe9ce
          target:
            fieldId: fct_habit_is_completed
          values:
            - new
          operator: equals
          required: false
  sorts:
    - fieldId: fct_habit_scheduled_date_day
      descending: true
  limit: 500
  metricOverrides: {}
  tableCalculations: []
  additionalMetrics: []
  customDimensions: []
chartConfig:
  type: pie
  config:
    isDonut: true
    metricId: fct_habit_total_task_instances
    showValue: true
    showLegend: true
    valueLabel: inside
    groupFieldIds:
      - dim_project_todoist_name
    legendPosition: horizontal
    showPercentage: false
    groupSortOverrides: []
    groupColorOverrides: {}
    groupLabelOverrides: {}
    legendMaxItemLength: 30
    groupValueOptionOverrides: {}
slug: todoist-completion-rate-today
tableConfig:
  columnOrder:
    - dim_project_todoist_name
    - fct_habit_is_completed
    - fct_habit_scheduled_date_day
    - fct_habit_total_task_instances
spaceSlug: shared
version: 1
downloadedAt: "2025-11-02T02:57:41.980Z"
