name: what did you do?
description: ""
tableName: fct_tasks
updatedAt: "2025-09-24T22:45:38.122Z"
metricQuery:
  exploreName: fct_tasks
  dimensions:
    - fct_tasks_completed_time_day
    - fct_tasks_completed_time_day_of_week_name
    - fct_tasks_gtd_work_type
    - dim_projects_project_name
    - fct_tasks_title
    - fct_tasks_task_id
    - dim_projects_project_id
    - fct_tasks_updated_time_raw
  metrics: []
  filters:
    dimensions:
      id: bc88410a-02ed-4333-ae94-0701ebc50b93
      and:
        - id: 493c28aa-ecd1-4647-b6bf-054c7a4e1b3b
          target:
            fieldId: fct_tasks_completed_time_day
          values:
            - 2
          operator: inThePast
          required: false
          settings:
            completed: false
            unitOfTime: days
        - id: 2340db70-1950-4b25-87b5-2f89aa3a05f8
          target:
            fieldId: dim_projects_completed_time_raw
          values:
            - "2025-09-23"
          operator: isNull
          required: false
  sorts:
    - fieldId: fct_tasks_completed_time_day
      descending: true
    - fieldId: fct_tasks_updated_time_raw
      descending: true
  limit: 100
  metricOverrides: {}
  tableCalculations: []
  additionalMetrics: []
  customDimensions: []
chartConfig:
  type: table
  config:
    columns:
      fct_tasks_title:
        name: task
      fct_tasks_task_id:
        visible: false
      dim_projects_project_id:
        visible: false
      fct_tasks_gtd_work_type:
        name: " "
      dim_projects_project_name:
        name: project
      fct_tasks_updated_time_raw:
        visible: false
      fct_tasks_completed_time_day:
        name: date
      fct_tasks_completed_time_day_of_week_name:
        name: day
    metricsAsRows: false
    showSubtotals: false
    hideRowNumbers: true
    showTableNames: false
    showResultsTotal: false
    showRowCalculation: false
    showColumnCalculation: false
    conditionalFormattings: []
slug: what-did-you-do
tableConfig:
  columnOrder:
    - fct_tasks_completed_time_day
    - fct_tasks_completed_time_day_of_week_name
    - fct_tasks_gtd_work_type
    - dim_projects_project_name
    - fct_tasks_title
    - fct_tasks_task_id
    - dim_projects_project_id
    - fct_tasks_updated_time_raw
spaceSlug: shared
version: 1
downloadedAt: "2025-09-24T23:16:20.099Z"
